-- MySQL Script generated by MySQL Workbench
-- Tue Mar  8 13:41:47 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema confort_unlimited_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema confort_unlimited_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `confort_unlimited_db` DEFAULT CHARACTER SET utf8 ;
USE `confort_unlimited_db` ;

-- -----------------------------------------------------
-- Table `confort_unlimited_db`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `confort_unlimited_db`.`users` (
  `iduser` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(100) NOT NULL,
  `phone` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`iduser`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `confort_unlimited_db`.`drivers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `confort_unlimited_db`.`drivers` (
  `iddriver` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `plate_number` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`iddriver`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `confort_unlimited_db`.`travels`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `confort_unlimited_db`.`travels` (
  `idtravel` INT NOT NULL AUTO_INCREMENT,
  `users_iduser` INT NOT NULL,
  `origin` VARCHAR(200) NOT NULL,
  `destination` VARCHAR(200) NOT NULL,
  `origin_lat` DOUBLE NOT NULL,
  `origin_lng` DOUBLE NOT NULL,
  `destination_lat` DOUBLE NOT NULL,
  `destination_lng` DOUBLE NOT NULL,
  `price` DOUBLE NOT NULL,
  `status` TINYINT NOT NULL,
  `date` DATETIME NOT NULL,
  `drivers_iddriver` INT NOT NULL,
  `folio` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idtravel`),
  INDEX `fk_travels_users_idx` (`users_iduser` ASC),
  INDEX `fk_travels_drivers1_idx` (`drivers_iddriver` ASC),
  CONSTRAINT `fk_travels_users`
    FOREIGN KEY (`users_iduser`)
    REFERENCES `confort_unlimited_db`.`users` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_travels_drivers1`
    FOREIGN KEY (`drivers_iddriver`)
    REFERENCES `confort_unlimited_db`.`drivers` (`iddriver`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `confort_unlimited_db`.`shared_travels`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `confort_unlimited_db`.`shared_travels` (
  `idshared_travel` INT NOT NULL AUTO_INCREMENT,
  `travels_idtravel` INT NOT NULL,
  `users_iduser` INT NOT NULL,
  `origin` VARCHAR(200) NOT NULL,
  `destination` VARCHAR(200) NOT NULL,
  `origin_lat` DOUBLE NOT NULL,
  `origin_lng` DOUBLE NOT NULL,
  `destination_lat` DOUBLE NOT NULL,
  `destination_lng` DOUBLE NOT NULL,
  `price` DOUBLE NOT NULL,
  `status` TINYINT NOT NULL,
  `folio` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idshared_travel`),
  INDEX `fk_shared_travels_travels1_idx` (`travels_idtravel` ASC),
  INDEX `fk_shared_travels_users1_idx` (`users_iduser` ASC),
  CONSTRAINT `fk_shared_travels_travels1`
    FOREIGN KEY (`travels_idtravel`)
    REFERENCES `confort_unlimited_db`.`travels` (`idtravel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_shared_travels_users1`
    FOREIGN KEY (`users_iduser`)
    REFERENCES `confort_unlimited_db`.`users` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `confort_unlimited_db`.`shared_codes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `confort_unlimited_db`.`shared_codes` (
  `idshared_codes` INT NOT NULL AUTO_INCREMENT,
  `travels_idtravel` INT NOT NULL,
  `shares` INT NOT NULL,
  PRIMARY KEY (`idshared_codes`),
  INDEX `fk_shared_codes_travels1_idx` (`travels_idtravel` ASC),
  CONSTRAINT `fk_shared_codes_travels1`
    FOREIGN KEY (`travels_idtravel`)
    REFERENCES `confort_unlimited_db`.`travels` (`idtravel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
